/*
 * generated by Xtext 2.25.0
 */
package com.wamas.ide.launching.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import com.wamas.ide.launching.ide.contentassist.antlr.internal.InternalLcDslParser;
import com.wamas.ide.launching.services.LcDslGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class LcDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(LcDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, LcDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getMainProjectAccess().getAlternatives_1(), "rule__MainProject__Alternatives_1");
			builder.put(grammarAccess.getPathAccess().getAlternatives(), "rule__Path__Alternatives");
			builder.put(grammarAccess.getClearOptionAccess().getAlternatives_2_0_0(), "rule__ClearOption__Alternatives_2_0_0");
			builder.put(grammarAccess.getGroupPostLaunchActionAccess().getAlternatives(), "rule__GroupPostLaunchAction__Alternatives");
			builder.put(grammarAccess.getBrowserLaunchModeAccess().getAlternatives(), "rule__BrowserLaunchMode__Alternatives");
			builder.put(grammarAccess.getLaunchConfigTypeAccess().getAlternatives(), "rule__LaunchConfigType__Alternatives");
			builder.put(grammarAccess.getLaunchModeTypeAccess().getAlternatives(), "rule__LaunchModeType__Alternatives");
			builder.put(grammarAccess.getMemoryUnitAccess().getAlternatives(), "rule__MemoryUnit__Alternatives");
			builder.put(grammarAccess.getOutputStreamAccess().getAlternatives(), "rule__OutputStream__Alternatives");
			builder.put(grammarAccess.getTestRunnerTypeAccess().getAlternatives(), "rule__TestRunnerType__Alternatives");
			builder.put(grammarAccess.getLaunchConfigAccess().getGroup(), "rule__LaunchConfig__Group__0");
			builder.put(grammarAccess.getLaunchConfigAccess().getGroup_0_11(), "rule__LaunchConfig__Group_0_11__0");
			builder.put(grammarAccess.getLaunchConfigAccess().getGroup_0_11_1(), "rule__LaunchConfig__Group_0_11_1__0");
			builder.put(grammarAccess.getLaunchConfigAccess().getGroup_4(), "rule__LaunchConfig__Group_4__0");
			builder.put(grammarAccess.getWorkspaceAccess().getGroup(), "rule__Workspace__Group__0");
			builder.put(grammarAccess.getWorkingDirAccess().getGroup(), "rule__WorkingDir__Group__0");
			builder.put(grammarAccess.getMainProjectAccess().getGroup(), "rule__MainProject__Group__0");
			builder.put(grammarAccess.getMainTypeAccess().getGroup(), "rule__MainType__Group__0");
			builder.put(grammarAccess.getAddPluginAccess().getGroup(), "rule__AddPlugin__Group__0");
			builder.put(grammarAccess.getAddFeatureAccess().getGroup(), "rule__AddFeature__Group__0");
			builder.put(grammarAccess.getContentProviderProductAccess().getGroup(), "rule__ContentProviderProduct__Group__0");
			builder.put(grammarAccess.getIgnorePluginAccess().getGroup(), "rule__IgnorePlugin__Group__0");
			builder.put(grammarAccess.getVmArgumentAccess().getGroup(), "rule__VmArgument__Group__0");
			builder.put(grammarAccess.getProgramArgumentAccess().getGroup(), "rule__ProgramArgument__Group__0");
			builder.put(grammarAccess.getEnvironmentVariableAccess().getGroup(), "rule__EnvironmentVariable__Group__0");
			builder.put(grammarAccess.getApplicationExtPointAccess().getGroup(), "rule__ApplicationExtPoint__Group__0");
			builder.put(grammarAccess.getProductExtPointAccess().getGroup(), "rule__ProductExtPoint__Group__0");
			builder.put(grammarAccess.getFavoritesAccess().getGroup(), "rule__Favorites__Group__0");
			builder.put(grammarAccess.getRedirectAccess().getGroup(), "rule__Redirect__Group__0");
			builder.put(grammarAccess.getRedirectAccess().getGroup_2_0(), "rule__Redirect__Group_2_0__0");
			builder.put(grammarAccess.getRedirectAccess().getGroup_2_1(), "rule__Redirect__Group_2_1__0");
			builder.put(grammarAccess.getExecutionEnvironmentAccess().getGroup(), "rule__ExecutionEnvironment__Group__0");
			builder.put(grammarAccess.getConfigIniTemplateAccess().getGroup(), "rule__ConfigIniTemplate__Group__0");
			builder.put(grammarAccess.getTraceEnablementAccess().getGroup(), "rule__TraceEnablement__Group__0");
			builder.put(grammarAccess.getJavaMainSearchAccess().getGroup(), "rule__JavaMainSearch__Group__0");
			builder.put(grammarAccess.getRapServletConfigAccess().getGroup(), "rule__RapServletConfig__Group__0");
			builder.put(grammarAccess.getRapServletConfigAccess().getGroup_2_0(), "rule__RapServletConfig__Group_2_0__0");
			builder.put(grammarAccess.getRapServletConfigAccess().getGroup_2_1(), "rule__RapServletConfig__Group_2_1__0");
			builder.put(grammarAccess.getRapServletConfigAccess().getGroup_2_2(), "rule__RapServletConfig__Group_2_2__0");
			builder.put(grammarAccess.getRapServletConfigAccess().getGroup_2_3(), "rule__RapServletConfig__Group_2_3__0");
			builder.put(grammarAccess.getRapServletConfigAccess().getGroup_2_4(), "rule__RapServletConfig__Group_2_4__0");
			builder.put(grammarAccess.getRapServletConfigAccess().getGroup_2_5(), "rule__RapServletConfig__Group_2_5__0");
			builder.put(grammarAccess.getPluginWithVersionAndStartLevelAccess().getGroup(), "rule__PluginWithVersionAndStartLevel__Group__0");
			builder.put(grammarAccess.getPluginWithVersionAndStartLevelAccess().getGroup_1_1(), "rule__PluginWithVersionAndStartLevel__Group_1_1__0");
			builder.put(grammarAccess.getPluginWithVersionAccess().getGroup(), "rule__PluginWithVersion__Group__0");
			builder.put(grammarAccess.getFeatureWithVersionAccess().getGroup(), "rule__FeatureWithVersion__Group__0");
			builder.put(grammarAccess.getClearOptionAccess().getGroup(), "rule__ClearOption__Group__0");
			builder.put(grammarAccess.getClearOptionAccess().getGroup_2_0(), "rule__ClearOption__Group_2_0__0");
			builder.put(grammarAccess.getMemoryOptionAccess().getGroup(), "rule__MemoryOption__Group__0");
			builder.put(grammarAccess.getMemoryOptionAccess().getGroup_2_0(), "rule__MemoryOption__Group_2_0__0");
			builder.put(grammarAccess.getMemoryOptionAccess().getGroup_2_1(), "rule__MemoryOption__Group_2_1__0");
			builder.put(grammarAccess.getMemoryOptionAccess().getGroup_2_2(), "rule__MemoryOption__Group_2_2__0");
			builder.put(grammarAccess.getGroupMemberAccess().getGroup(), "rule__GroupMember__Group__0");
			builder.put(grammarAccess.getGroupPostLaunchDelayAccess().getGroup(), "rule__GroupPostLaunchDelay__Group__0");
			builder.put(grammarAccess.getGroupPostLaunchRegexAccess().getGroup(), "rule__GroupPostLaunchRegex__Group__0");
			builder.put(grammarAccess.getGroupPostLaunchWaitAccess().getGroup(), "rule__GroupPostLaunchWait__Group__0");
			builder.put(grammarAccess.getTestConfigAccess().getGroup(), "rule__TestConfig__Group__0");
			builder.put(grammarAccess.getTestConfigAccess().getGroup_3_0(), "rule__TestConfig__Group_3_0__0");
			builder.put(grammarAccess.getTestConfigAccess().getGroup_3_1(), "rule__TestConfig__Group_3_1__0");
			builder.put(grammarAccess.getTestConfigAccess().getGroup_3_2(), "rule__TestConfig__Group_3_2__0");
			builder.put(grammarAccess.getTestConfigAccess().getGroup_3_3(), "rule__TestConfig__Group_3_3__0");
			builder.put(grammarAccess.getTestConfigAccess().getGroup_3_4(), "rule__TestConfig__Group_3_4__0");
			builder.put(grammarAccess.getTestConfigAccess().getGroup_3_5(), "rule__TestConfig__Group_3_5__0");
			builder.put(grammarAccess.getFQNameAccess().getGroup(), "rule__FQName__Group__0");
			builder.put(grammarAccess.getFQNameAccess().getGroup_1(), "rule__FQName__Group_1__0");
			builder.put(grammarAccess.getTagsAccess().getGroup(), "rule__Tags__Group__0");
			builder.put(grammarAccess.getTagsAccess().getGroup_1(), "rule__Tags__Group_1__0");
			builder.put(grammarAccess.getLCModelAccess().getConfigurationsAssignment(), "rule__LCModel__ConfigurationsAssignment");
			builder.put(grammarAccess.getLaunchConfigAccess().getExplicitAssignment_0_0(), "rule__LaunchConfig__ExplicitAssignment_0_0");
			builder.put(grammarAccess.getLaunchConfigAccess().getManualAssignment_0_1(), "rule__LaunchConfig__ManualAssignment_0_1");
			builder.put(grammarAccess.getLaunchConfigAccess().getAbstractAssignment_0_2(), "rule__LaunchConfig__AbstractAssignment_0_2");
			builder.put(grammarAccess.getLaunchConfigAccess().getForegroundAssignment_0_3(), "rule__LaunchConfig__ForegroundAssignment_0_3");
			builder.put(grammarAccess.getLaunchConfigAccess().getNoConsoleAssignment_0_4(), "rule__LaunchConfig__NoConsoleAssignment_0_4");
			builder.put(grammarAccess.getLaunchConfigAccess().getNoValidateAssignment_0_5(), "rule__LaunchConfig__NoValidateAssignment_0_5");
			builder.put(grammarAccess.getLaunchConfigAccess().getSwInstallSupportAssignment_0_6(), "rule__LaunchConfig__SwInstallSupportAssignment_0_6");
			builder.put(grammarAccess.getLaunchConfigAccess().getReplaceEnvAssignment_0_7(), "rule__LaunchConfig__ReplaceEnvAssignment_0_7");
			builder.put(grammarAccess.getLaunchConfigAccess().getStopInMainAssignment_0_8(), "rule__LaunchConfig__StopInMainAssignment_0_8");
			builder.put(grammarAccess.getLaunchConfigAccess().getKeepRunningAssignment_0_9(), "rule__LaunchConfig__KeepRunningAssignment_0_9");
			builder.put(grammarAccess.getLaunchConfigAccess().getRunInUiThreadAssignment_0_10(), "rule__LaunchConfig__RunInUiThreadAssignment_0_10");
			builder.put(grammarAccess.getLaunchConfigAccess().getQualifyAssignment_0_11_0(), "rule__LaunchConfig__QualifyAssignment_0_11_0");
			builder.put(grammarAccess.getLaunchConfigAccess().getQualifierIdAssignment_0_11_1_1(), "rule__LaunchConfig__QualifierIdAssignment_0_11_1_1");
			builder.put(grammarAccess.getLaunchConfigAccess().getTypeAssignment_1(), "rule__LaunchConfig__TypeAssignment_1");
			builder.put(grammarAccess.getLaunchConfigAccess().getNameAssignment_3(), "rule__LaunchConfig__NameAssignment_3");
			builder.put(grammarAccess.getLaunchConfigAccess().getSuperConfigAssignment_4_1(), "rule__LaunchConfig__SuperConfigAssignment_4_1");
			builder.put(grammarAccess.getLaunchConfigAccess().getClearsAssignment_6_0(), "rule__LaunchConfig__ClearsAssignment_6_0");
			builder.put(grammarAccess.getLaunchConfigAccess().getWorkspaceAssignment_6_1(), "rule__LaunchConfig__WorkspaceAssignment_6_1");
			builder.put(grammarAccess.getLaunchConfigAccess().getWorkingDirAssignment_6_2(), "rule__LaunchConfig__WorkingDirAssignment_6_2");
			builder.put(grammarAccess.getLaunchConfigAccess().getMemoryAssignment_6_3(), "rule__LaunchConfig__MemoryAssignment_6_3");
			builder.put(grammarAccess.getLaunchConfigAccess().getMainProjectAssignment_6_4(), "rule__LaunchConfig__MainProjectAssignment_6_4");
			builder.put(grammarAccess.getLaunchConfigAccess().getMainTypeAssignment_6_5(), "rule__LaunchConfig__MainTypeAssignment_6_5");
			builder.put(grammarAccess.getLaunchConfigAccess().getApplicationAssignment_6_6(), "rule__LaunchConfig__ApplicationAssignment_6_6");
			builder.put(grammarAccess.getLaunchConfigAccess().getProductAssignment_6_7(), "rule__LaunchConfig__ProductAssignment_6_7");
			builder.put(grammarAccess.getLaunchConfigAccess().getFavoritesAssignment_6_8(), "rule__LaunchConfig__FavoritesAssignment_6_8");
			builder.put(grammarAccess.getLaunchConfigAccess().getRedirectAssignment_6_9(), "rule__LaunchConfig__RedirectAssignment_6_9");
			builder.put(grammarAccess.getLaunchConfigAccess().getExecEnvAssignment_6_10(), "rule__LaunchConfig__ExecEnvAssignment_6_10");
			builder.put(grammarAccess.getLaunchConfigAccess().getConfigIniTemplateAssignment_6_11(), "rule__LaunchConfig__ConfigIniTemplateAssignment_6_11");
			builder.put(grammarAccess.getLaunchConfigAccess().getJavaMainSearchAssignment_6_12(), "rule__LaunchConfig__JavaMainSearchAssignment_6_12");
			builder.put(grammarAccess.getLaunchConfigAccess().getServletConfigAssignment_6_13(), "rule__LaunchConfig__ServletConfigAssignment_6_13");
			builder.put(grammarAccess.getLaunchConfigAccess().getContentProviderProductAssignment_6_14(), "rule__LaunchConfig__ContentProviderProductAssignment_6_14");
			builder.put(grammarAccess.getLaunchConfigAccess().getTestAssignment_6_15(), "rule__LaunchConfig__TestAssignment_6_15");
			builder.put(grammarAccess.getLaunchConfigAccess().getPluginsAssignment_6_16(), "rule__LaunchConfig__PluginsAssignment_6_16");
			builder.put(grammarAccess.getLaunchConfigAccess().getFeaturesAssignment_6_17(), "rule__LaunchConfig__FeaturesAssignment_6_17");
			builder.put(grammarAccess.getLaunchConfigAccess().getIgnoreAssignment_6_18(), "rule__LaunchConfig__IgnoreAssignment_6_18");
			builder.put(grammarAccess.getLaunchConfigAccess().getGroupMembersAssignment_6_19(), "rule__LaunchConfig__GroupMembersAssignment_6_19");
			builder.put(grammarAccess.getLaunchConfigAccess().getVmArgsAssignment_6_20(), "rule__LaunchConfig__VmArgsAssignment_6_20");
			builder.put(grammarAccess.getLaunchConfigAccess().getProgArgsAssignment_6_21(), "rule__LaunchConfig__ProgArgsAssignment_6_21");
			builder.put(grammarAccess.getLaunchConfigAccess().getEnvVarsAssignment_6_22(), "rule__LaunchConfig__EnvVarsAssignment_6_22");
			builder.put(grammarAccess.getLaunchConfigAccess().getTracesAssignment_6_23(), "rule__LaunchConfig__TracesAssignment_6_23");
			builder.put(grammarAccess.getWorkspaceAccess().getWorkspaceAssignment_1(), "rule__Workspace__WorkspaceAssignment_1");
			builder.put(grammarAccess.getWorkingDirAccess().getWorkingDirAssignment_1(), "rule__WorkingDir__WorkingDirAssignment_1");
			builder.put(grammarAccess.getMainProjectAccess().getSelfAssignment_1_0(), "rule__MainProject__SelfAssignment_1_0");
			builder.put(grammarAccess.getMainProjectAccess().getProjectAssignment_1_1(), "rule__MainProject__ProjectAssignment_1_1");
			builder.put(grammarAccess.getMainTypeAccess().getMainClassAssignment_1(), "rule__MainType__MainClassAssignment_1");
			builder.put(grammarAccess.getAddPluginAccess().getOptionalAssignment_0(), "rule__AddPlugin__OptionalAssignment_0");
			builder.put(grammarAccess.getAddPluginAccess().getPluginAssignment_2(), "rule__AddPlugin__PluginAssignment_2");
			builder.put(grammarAccess.getAddFeatureAccess().getOptionalAssignment_0(), "rule__AddFeature__OptionalAssignment_0");
			builder.put(grammarAccess.getAddFeatureAccess().getFeatureAssignment_2(), "rule__AddFeature__FeatureAssignment_2");
			builder.put(grammarAccess.getContentProviderProductAccess().getProductAssignment_1(), "rule__ContentProviderProduct__ProductAssignment_1");
			builder.put(grammarAccess.getIgnorePluginAccess().getPluginAssignment_1(), "rule__IgnorePlugin__PluginAssignment_1");
			builder.put(grammarAccess.getVmArgumentAccess().getArgumentsAssignment_2(), "rule__VmArgument__ArgumentsAssignment_2");
			builder.put(grammarAccess.getProgramArgumentAccess().getArgumentsAssignment_2(), "rule__ProgramArgument__ArgumentsAssignment_2");
			builder.put(grammarAccess.getEnvironmentVariableAccess().getNameAssignment_2(), "rule__EnvironmentVariable__NameAssignment_2");
			builder.put(grammarAccess.getEnvironmentVariableAccess().getValueAssignment_4(), "rule__EnvironmentVariable__ValueAssignment_4");
			builder.put(grammarAccess.getApplicationExtPointAccess().getNameAssignment_1(), "rule__ApplicationExtPoint__NameAssignment_1");
			builder.put(grammarAccess.getProductExtPointAccess().getNameAssignment_1(), "rule__ProductExtPoint__NameAssignment_1");
			builder.put(grammarAccess.getFavoritesAccess().getTypesAssignment_2(), "rule__Favorites__TypesAssignment_2");
			builder.put(grammarAccess.getRedirectAccess().getOutWhichAssignment_2_0_0(), "rule__Redirect__OutWhichAssignment_2_0_0");
			builder.put(grammarAccess.getRedirectAccess().getOutFileAssignment_2_0_2(), "rule__Redirect__OutFileAssignment_2_0_2");
			builder.put(grammarAccess.getRedirectAccess().getNoAppendAssignment_2_0_3(), "rule__Redirect__NoAppendAssignment_2_0_3");
			builder.put(grammarAccess.getRedirectAccess().getInWhichAssignment_2_1_0(), "rule__Redirect__InWhichAssignment_2_1_0");
			builder.put(grammarAccess.getRedirectAccess().getInFileAssignment_2_1_2(), "rule__Redirect__InFileAssignment_2_1_2");
			builder.put(grammarAccess.getExecutionEnvironmentAccess().getNameAssignment_1(), "rule__ExecutionEnvironment__NameAssignment_1");
			builder.put(grammarAccess.getConfigIniTemplateAccess().getPathAssignment_1(), "rule__ConfigIniTemplate__PathAssignment_1");
			builder.put(grammarAccess.getTraceEnablementAccess().getPluginAssignment_1(), "rule__TraceEnablement__PluginAssignment_1");
			builder.put(grammarAccess.getTraceEnablementAccess().getWhatAssignment_2(), "rule__TraceEnablement__WhatAssignment_2");
			builder.put(grammarAccess.getJavaMainSearchAccess().getSystemAssignment_2_0(), "rule__JavaMainSearch__SystemAssignment_2_0");
			builder.put(grammarAccess.getJavaMainSearchAccess().getInheritedAssignment_2_1(), "rule__JavaMainSearch__InheritedAssignment_2_1");
			builder.put(grammarAccess.getRapServletConfigAccess().getServletPathAssignment_2_0_1(), "rule__RapServletConfig__ServletPathAssignment_2_0_1");
			builder.put(grammarAccess.getRapServletConfigAccess().getBrowserModeAssignment_2_1_1(), "rule__RapServletConfig__BrowserModeAssignment_2_1_1");
			builder.put(grammarAccess.getRapServletConfigAccess().getServerPortAssignment_2_2_1(), "rule__RapServletConfig__ServerPortAssignment_2_2_1");
			builder.put(grammarAccess.getRapServletConfigAccess().getSessionTimeoutAssignment_2_3_1(), "rule__RapServletConfig__SessionTimeoutAssignment_2_3_1");
			builder.put(grammarAccess.getRapServletConfigAccess().getContextPathAssignment_2_4_1(), "rule__RapServletConfig__ContextPathAssignment_2_4_1");
			builder.put(grammarAccess.getRapServletConfigAccess().getDevModeAssignment_2_5_1(), "rule__RapServletConfig__DevModeAssignment_2_5_1");
			builder.put(grammarAccess.getExistingPathAccess().getNameAssignment(), "rule__ExistingPath__NameAssignment");
			builder.put(grammarAccess.getAnyPathAccess().getNameAssignment(), "rule__AnyPath__NameAssignment");
			builder.put(grammarAccess.getPluginWithVersionAndStartLevelAccess().getPluginAssignment_0(), "rule__PluginWithVersionAndStartLevel__PluginAssignment_0");
			builder.put(grammarAccess.getPluginWithVersionAndStartLevelAccess().getAutoStartAssignment_1_0(), "rule__PluginWithVersionAndStartLevel__AutoStartAssignment_1_0");
			builder.put(grammarAccess.getPluginWithVersionAndStartLevelAccess().getStartLevelAssignment_1_1_1(), "rule__PluginWithVersionAndStartLevel__StartLevelAssignment_1_1_1");
			builder.put(grammarAccess.getPluginWithVersionAccess().getNameAssignment_0(), "rule__PluginWithVersion__NameAssignment_0");
			builder.put(grammarAccess.getPluginWithVersionAccess().getVersionAssignment_1(), "rule__PluginWithVersion__VersionAssignment_1");
			builder.put(grammarAccess.getFeatureWithVersionAccess().getNameAssignment_0(), "rule__FeatureWithVersion__NameAssignment_0");
			builder.put(grammarAccess.getFeatureWithVersionAccess().getVersionAssignment_1(), "rule__FeatureWithVersion__VersionAssignment_1");
			builder.put(grammarAccess.getProjectAccess().getNameAssignment(), "rule__Project__NameAssignment");
			builder.put(grammarAccess.getJavaMainTypeAccess().getNameAssignment(), "rule__JavaMainType__NameAssignment");
			builder.put(grammarAccess.getClearOptionAccess().getWorkspaceAssignment_2_0_0_0(), "rule__ClearOption__WorkspaceAssignment_2_0_0_0");
			builder.put(grammarAccess.getClearOptionAccess().getLogAssignment_2_0_0_1(), "rule__ClearOption__LogAssignment_2_0_0_1");
			builder.put(grammarAccess.getClearOptionAccess().getNoAskClearAssignment_2_0_1(), "rule__ClearOption__NoAskClearAssignment_2_0_1");
			builder.put(grammarAccess.getClearOptionAccess().getConfigAssignment_2_1(), "rule__ClearOption__ConfigAssignment_2_1");
			builder.put(grammarAccess.getMemoryOptionAccess().getMinAssignment_2_0_2(), "rule__MemoryOption__MinAssignment_2_0_2");
			builder.put(grammarAccess.getMemoryOptionAccess().getMinUnitAssignment_2_0_3(), "rule__MemoryOption__MinUnitAssignment_2_0_3");
			builder.put(grammarAccess.getMemoryOptionAccess().getMaxAssignment_2_1_2(), "rule__MemoryOption__MaxAssignment_2_1_2");
			builder.put(grammarAccess.getMemoryOptionAccess().getMaxUnitAssignment_2_1_3(), "rule__MemoryOption__MaxUnitAssignment_2_1_3");
			builder.put(grammarAccess.getMemoryOptionAccess().getPermAssignment_2_2_2(), "rule__MemoryOption__PermAssignment_2_2_2");
			builder.put(grammarAccess.getMemoryOptionAccess().getPermUnitAssignment_2_2_3(), "rule__MemoryOption__PermUnitAssignment_2_2_3");
			builder.put(grammarAccess.getGroupMemberAccess().getTypeAssignment_0_0(), "rule__GroupMember__TypeAssignment_0_0");
			builder.put(grammarAccess.getGroupMemberAccess().getAdoptAssignment_0_1(), "rule__GroupMember__AdoptAssignment_0_1");
			builder.put(grammarAccess.getGroupMemberAccess().getMemberAssignment_2(), "rule__GroupMember__MemberAssignment_2");
			builder.put(grammarAccess.getGroupMemberAccess().getPostActionAssignment_3(), "rule__GroupMember__PostActionAssignment_3");
			builder.put(grammarAccess.getGroupPostLaunchDelayAccess().getDelayAssignment_1(), "rule__GroupPostLaunchDelay__DelayAssignment_1");
			builder.put(grammarAccess.getGroupPostLaunchRegexAccess().getRegexAssignment_1(), "rule__GroupPostLaunchRegex__RegexAssignment_1");
			builder.put(grammarAccess.getStringWithVariablesAccess().getValueAssignment(), "rule__StringWithVariables__ValueAssignment");
			builder.put(grammarAccess.getTestConfigAccess().getRunnerAssignment_3_0_1(), "rule__TestConfig__RunnerAssignment_3_0_1");
			builder.put(grammarAccess.getTestConfigAccess().getContainerAssignment_3_1_1(), "rule__TestConfig__ContainerAssignment_3_1_1");
			builder.put(grammarAccess.getTestConfigAccess().getClassAssignment_3_2_1(), "rule__TestConfig__ClassAssignment_3_2_1");
			builder.put(grammarAccess.getTestConfigAccess().getMethodAssignment_3_3_1(), "rule__TestConfig__MethodAssignment_3_3_1");
			builder.put(grammarAccess.getTestConfigAccess().getExcludeTagsAssignment_3_4_1(), "rule__TestConfig__ExcludeTagsAssignment_3_4_1");
			builder.put(grammarAccess.getTestConfigAccess().getIncludeTagsAssignment_3_5_1(), "rule__TestConfig__IncludeTagsAssignment_3_5_1");
			builder.put(grammarAccess.getLaunchConfigAccess().getUnorderedGroup_0(), "rule__LaunchConfig__UnorderedGroup_0");
			builder.put(grammarAccess.getLaunchConfigAccess().getUnorderedGroup_6(), "rule__LaunchConfig__UnorderedGroup_6");
			builder.put(grammarAccess.getRedirectAccess().getUnorderedGroup_2(), "rule__Redirect__UnorderedGroup_2");
			builder.put(grammarAccess.getJavaMainSearchAccess().getUnorderedGroup_2(), "rule__JavaMainSearch__UnorderedGroup_2");
			builder.put(grammarAccess.getRapServletConfigAccess().getUnorderedGroup_2(), "rule__RapServletConfig__UnorderedGroup_2");
			builder.put(grammarAccess.getPluginWithVersionAndStartLevelAccess().getUnorderedGroup_1(), "rule__PluginWithVersionAndStartLevel__UnorderedGroup_1");
			builder.put(grammarAccess.getClearOptionAccess().getUnorderedGroup_2(), "rule__ClearOption__UnorderedGroup_2");
			builder.put(grammarAccess.getMemoryOptionAccess().getUnorderedGroup_2(), "rule__MemoryOption__UnorderedGroup_2");
			builder.put(grammarAccess.getGroupMemberAccess().getUnorderedGroup_0(), "rule__GroupMember__UnorderedGroup_0");
			builder.put(grammarAccess.getTestConfigAccess().getUnorderedGroup_3(), "rule__TestConfig__UnorderedGroup_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private LcDslGrammarAccess grammarAccess;

	@Override
	protected InternalLcDslParser createParser() {
		InternalLcDslParser result = new InternalLcDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public LcDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LcDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
