/**
 * generated by Xtext 2.10.0
 */
package com.wamas.ide.launching.lcDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Content Provider Product</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.wamas.ide.launching.lcDsl.ContentProviderProduct#getProduct <em>Product</em>}</li>
 * </ul>
 *
 * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getContentProviderProduct()
 * @model
 * @generated
 */
public interface ContentProviderProduct extends EObject
{
  /**
   * Returns the value of the '<em><b>Product</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Product</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Product</em>' containment reference.
   * @see #setProduct(ExistingPath)
   * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getContentProviderProduct_Product()
   * @model containment="true"
   * @generated
   */
  ExistingPath getProduct();

  /**
   * Sets the value of the '{@link com.wamas.ide.launching.lcDsl.ContentProviderProduct#getProduct <em>Product</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Product</em>' containment reference.
   * @see #getProduct()
   * @generated
   */
  void setProduct(ExistingPath value);

} // ContentProviderProduct
