/**
 * generated by Xtext 2.10.0
 */
package com.wamas.ide.launching.lcDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Favorites</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.wamas.ide.launching.lcDsl.Favorites#isRun <em>Run</em>}</li>
 *   <li>{@link com.wamas.ide.launching.lcDsl.Favorites#isDebug <em>Debug</em>}</li>
 * </ul>
 *
 * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getFavorites()
 * @model
 * @generated
 */
public interface Favorites extends EObject
{
  /**
   * Returns the value of the '<em><b>Run</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Run</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Run</em>' attribute.
   * @see #setRun(boolean)
   * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getFavorites_Run()
   * @model
   * @generated
   */
  boolean isRun();

  /**
   * Sets the value of the '{@link com.wamas.ide.launching.lcDsl.Favorites#isRun <em>Run</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Run</em>' attribute.
   * @see #isRun()
   * @generated
   */
  void setRun(boolean value);

  /**
   * Returns the value of the '<em><b>Debug</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Debug</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Debug</em>' attribute.
   * @see #setDebug(boolean)
   * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getFavorites_Debug()
   * @model
   * @generated
   */
  boolean isDebug();

  /**
   * Sets the value of the '{@link com.wamas.ide.launching.lcDsl.Favorites#isDebug <em>Debug</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Debug</em>' attribute.
   * @see #isDebug()
   * @generated
   */
  void setDebug(boolean value);

} // Favorites
