/**
 * generated by Xtext 2.10.0
 */
package com.wamas.ide.launching.lcDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Java Main Search</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.wamas.ide.launching.lcDsl.JavaMainSearch#isSystem <em>System</em>}</li>
 *   <li>{@link com.wamas.ide.launching.lcDsl.JavaMainSearch#isInherited <em>Inherited</em>}</li>
 * </ul>
 *
 * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getJavaMainSearch()
 * @model
 * @generated
 */
public interface JavaMainSearch extends EObject
{
  /**
   * Returns the value of the '<em><b>System</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>System</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>System</em>' attribute.
   * @see #setSystem(boolean)
   * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getJavaMainSearch_System()
   * @model
   * @generated
   */
  boolean isSystem();

  /**
   * Sets the value of the '{@link com.wamas.ide.launching.lcDsl.JavaMainSearch#isSystem <em>System</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>System</em>' attribute.
   * @see #isSystem()
   * @generated
   */
  void setSystem(boolean value);

  /**
   * Returns the value of the '<em><b>Inherited</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Inherited</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inherited</em>' attribute.
   * @see #setInherited(boolean)
   * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getJavaMainSearch_Inherited()
   * @model
   * @generated
   */
  boolean isInherited();

  /**
   * Sets the value of the '{@link com.wamas.ide.launching.lcDsl.JavaMainSearch#isInherited <em>Inherited</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inherited</em>' attribute.
   * @see #isInherited()
   * @generated
   */
  void setInherited(boolean value);

} // JavaMainSearch
