/**
 * generated by Xtext 2.28.0
 */
package com.wamas.ide.launching.lcDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LC Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.wamas.ide.launching.lcDsl.LCModel#getConfigurations <em>Configurations</em>}</li>
 * </ul>
 *
 * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getLCModel()
 * @model
 * @generated
 */
public interface LCModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Configurations</b></em>' containment reference list.
   * The list contents are of type {@link com.wamas.ide.launching.lcDsl.LaunchConfig}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Configurations</em>' containment reference list.
   * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getLCModel_Configurations()
   * @model containment="true"
   * @generated
   */
  EList<LaunchConfig> getConfigurations();

} // LCModel
