/**
 * generated by Xtext 2.25.0
 */
package com.wamas.ide.launching.lcDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Plugin With Version And Start Level</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.wamas.ide.launching.lcDsl.PluginWithVersionAndStartLevel#getPlugin <em>Plugin</em>}</li>
 *   <li>{@link com.wamas.ide.launching.lcDsl.PluginWithVersionAndStartLevel#isAutoStart <em>Auto Start</em>}</li>
 *   <li>{@link com.wamas.ide.launching.lcDsl.PluginWithVersionAndStartLevel#getStartLevel <em>Start Level</em>}</li>
 * </ul>
 *
 * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getPluginWithVersionAndStartLevel()
 * @model
 * @generated
 */
public interface PluginWithVersionAndStartLevel extends EObject
{
  /**
   * Returns the value of the '<em><b>Plugin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plugin</em>' containment reference.
   * @see #setPlugin(PluginWithVersion)
   * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getPluginWithVersionAndStartLevel_Plugin()
   * @model containment="true"
   * @generated
   */
  PluginWithVersion getPlugin();

  /**
   * Sets the value of the '{@link com.wamas.ide.launching.lcDsl.PluginWithVersionAndStartLevel#getPlugin <em>Plugin</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plugin</em>' containment reference.
   * @see #getPlugin()
   * @generated
   */
  void setPlugin(PluginWithVersion value);

  /**
   * Returns the value of the '<em><b>Auto Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Auto Start</em>' attribute.
   * @see #setAutoStart(boolean)
   * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getPluginWithVersionAndStartLevel_AutoStart()
   * @model
   * @generated
   */
  boolean isAutoStart();

  /**
   * Sets the value of the '{@link com.wamas.ide.launching.lcDsl.PluginWithVersionAndStartLevel#isAutoStart <em>Auto Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Auto Start</em>' attribute.
   * @see #isAutoStart()
   * @generated
   */
  void setAutoStart(boolean value);

  /**
   * Returns the value of the '<em><b>Start Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Level</em>' attribute.
   * @see #setStartLevel(int)
   * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getPluginWithVersionAndStartLevel_StartLevel()
   * @model
   * @generated
   */
  int getStartLevel();

  /**
   * Sets the value of the '{@link com.wamas.ide.launching.lcDsl.PluginWithVersionAndStartLevel#getStartLevel <em>Start Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Level</em>' attribute.
   * @see #getStartLevel()
   * @generated
   */
  void setStartLevel(int value);

} // PluginWithVersionAndStartLevel
