/**
 * generated by Xtext 2.10.0
 */
package com.wamas.ide.launching.lcDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Redirect</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.wamas.ide.launching.lcDsl.Redirect#getOutWhich <em>Out Which</em>}</li>
 *   <li>{@link com.wamas.ide.launching.lcDsl.Redirect#getOutFile <em>Out File</em>}</li>
 *   <li>{@link com.wamas.ide.launching.lcDsl.Redirect#isNoAppend <em>No Append</em>}</li>
 *   <li>{@link com.wamas.ide.launching.lcDsl.Redirect#getInWhich <em>In Which</em>}</li>
 *   <li>{@link com.wamas.ide.launching.lcDsl.Redirect#getInFile <em>In File</em>}</li>
 * </ul>
 *
 * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getRedirect()
 * @model
 * @generated
 */
public interface Redirect extends EObject
{
  /**
   * Returns the value of the '<em><b>Out Which</b></em>' attribute.
   * The literals are from the enumeration {@link com.wamas.ide.launching.lcDsl.OutputStream}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Out Which</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Out Which</em>' attribute.
   * @see com.wamas.ide.launching.lcDsl.OutputStream
   * @see #setOutWhich(OutputStream)
   * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getRedirect_OutWhich()
   * @model
   * @generated
   */
  OutputStream getOutWhich();

  /**
   * Sets the value of the '{@link com.wamas.ide.launching.lcDsl.Redirect#getOutWhich <em>Out Which</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Out Which</em>' attribute.
   * @see com.wamas.ide.launching.lcDsl.OutputStream
   * @see #getOutWhich()
   * @generated
   */
  void setOutWhich(OutputStream value);

  /**
   * Returns the value of the '<em><b>Out File</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Out File</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Out File</em>' containment reference.
   * @see #setOutFile(AnyPath)
   * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getRedirect_OutFile()
   * @model containment="true"
   * @generated
   */
  AnyPath getOutFile();

  /**
   * Sets the value of the '{@link com.wamas.ide.launching.lcDsl.Redirect#getOutFile <em>Out File</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Out File</em>' containment reference.
   * @see #getOutFile()
   * @generated
   */
  void setOutFile(AnyPath value);

  /**
   * Returns the value of the '<em><b>No Append</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>No Append</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>No Append</em>' attribute.
   * @see #setNoAppend(boolean)
   * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getRedirect_NoAppend()
   * @model
   * @generated
   */
  boolean isNoAppend();

  /**
   * Sets the value of the '{@link com.wamas.ide.launching.lcDsl.Redirect#isNoAppend <em>No Append</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>No Append</em>' attribute.
   * @see #isNoAppend()
   * @generated
   */
  void setNoAppend(boolean value);

  /**
   * Returns the value of the '<em><b>In Which</b></em>' attribute.
   * The literals are from the enumeration {@link com.wamas.ide.launching.lcDsl.InputStream}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>In Which</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>In Which</em>' attribute.
   * @see com.wamas.ide.launching.lcDsl.InputStream
   * @see #setInWhich(InputStream)
   * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getRedirect_InWhich()
   * @model
   * @generated
   */
  InputStream getInWhich();

  /**
   * Sets the value of the '{@link com.wamas.ide.launching.lcDsl.Redirect#getInWhich <em>In Which</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>In Which</em>' attribute.
   * @see com.wamas.ide.launching.lcDsl.InputStream
   * @see #getInWhich()
   * @generated
   */
  void setInWhich(InputStream value);

  /**
   * Returns the value of the '<em><b>In File</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>In File</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>In File</em>' containment reference.
   * @see #setInFile(ExistingPath)
   * @see com.wamas.ide.launching.lcDsl.LcDslPackage#getRedirect_InFile()
   * @model containment="true"
   * @generated
   */
  ExistingPath getInFile();

  /**
   * Sets the value of the '{@link com.wamas.ide.launching.lcDsl.Redirect#getInFile <em>In File</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>In File</em>' containment reference.
   * @see #getInFile()
   * @generated
   */
  void setInFile(ExistingPath value);

} // Redirect
