/**
 * generated by Xtext 2.10.0
 */
package com.wamas.ide.launching.lcDsl.impl;

import com.wamas.ide.launching.lcDsl.LcDslPackage;
import com.wamas.ide.launching.lcDsl.PluginWithVersion;
import com.wamas.ide.launching.lcDsl.TraceEnablement;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Trace Enablement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.wamas.ide.launching.lcDsl.impl.TraceEnablementImpl#getPlugin <em>Plugin</em>}</li>
 *   <li>{@link com.wamas.ide.launching.lcDsl.impl.TraceEnablementImpl#getWhat <em>What</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TraceEnablementImpl extends MinimalEObjectImpl.Container implements TraceEnablement
{
  /**
   * The cached value of the '{@link #getPlugin() <em>Plugin</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPlugin()
   * @generated
   * @ordered
   */
  protected PluginWithVersion plugin;

  /**
   * The cached value of the '{@link #getWhat() <em>What</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWhat()
   * @generated
   * @ordered
   */
  protected EList<String> what;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TraceEnablementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LcDslPackage.Literals.TRACE_ENABLEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PluginWithVersion getPlugin()
  {
    return plugin;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPlugin(PluginWithVersion newPlugin, NotificationChain msgs)
  {
    PluginWithVersion oldPlugin = plugin;
    plugin = newPlugin;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LcDslPackage.TRACE_ENABLEMENT__PLUGIN, oldPlugin, newPlugin);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPlugin(PluginWithVersion newPlugin)
  {
    if (newPlugin != plugin)
    {
      NotificationChain msgs = null;
      if (plugin != null)
        msgs = ((InternalEObject)plugin).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LcDslPackage.TRACE_ENABLEMENT__PLUGIN, null, msgs);
      if (newPlugin != null)
        msgs = ((InternalEObject)newPlugin).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LcDslPackage.TRACE_ENABLEMENT__PLUGIN, null, msgs);
      msgs = basicSetPlugin(newPlugin, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LcDslPackage.TRACE_ENABLEMENT__PLUGIN, newPlugin, newPlugin));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getWhat()
  {
    if (what == null)
    {
      what = new EDataTypeEList<String>(String.class, this, LcDslPackage.TRACE_ENABLEMENT__WHAT);
    }
    return what;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LcDslPackage.TRACE_ENABLEMENT__PLUGIN:
        return basicSetPlugin(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LcDslPackage.TRACE_ENABLEMENT__PLUGIN:
        return getPlugin();
      case LcDslPackage.TRACE_ENABLEMENT__WHAT:
        return getWhat();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LcDslPackage.TRACE_ENABLEMENT__PLUGIN:
        setPlugin((PluginWithVersion)newValue);
        return;
      case LcDslPackage.TRACE_ENABLEMENT__WHAT:
        getWhat().clear();
        getWhat().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LcDslPackage.TRACE_ENABLEMENT__PLUGIN:
        setPlugin((PluginWithVersion)null);
        return;
      case LcDslPackage.TRACE_ENABLEMENT__WHAT:
        getWhat().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LcDslPackage.TRACE_ENABLEMENT__PLUGIN:
        return plugin != null;
      case LcDslPackage.TRACE_ENABLEMENT__WHAT:
        return what != null && !what.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (what: ");
    result.append(what);
    result.append(')');
    return result.toString();
  }

} //TraceEnablementImpl
