/*
 * generated by Xtext 2.12.0
 */
package com.wamas.ide.launching.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLcDslScopeProvider extends DelegatingScopeProvider {
}
